version: 0.1
env:
  variables:
    APP_NAME: "GDPR"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo install process started
      - npm install --force && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should upload to S3 now
      - cd dist/$APP_NAME
      - ls -la
      - aws s3 sync . s3://brocom.gdpr --delete
